{% set name = "ESMValTool" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdeac96ccf7ff7c67af19976a0c99991f06edd3d105e9b16079d0fd68f4a1ad9

build:
  number: 0

outputs:
  - name: esmvaltool-python
    build:
      noarch: python
      entry_points:
        - cmorize_obs = esmvaltool.cmorizers.obs.cmorize_obs:main
        - mip_convert_setup = esmvaltool.cmorizers.mip_convert.esmvt_mipconv_setup:main
        - nclcodestyle = esmvaltool.utils.nclcodestyle.nclcodestyle:_main
        - test_recipe = esmvaltool.utils.testing.recipe_settings.install_expand_run:main
        - recipe_filler = esmvaltool.utils.recipe_filler:run
    script: build_python.bat  # [win]
    script: build_python.sh  # [not win]
    requirements:
      build:
        - python >=3.7
        - pip
      host:
        - python >=3.7
        - setuptools_scm
        - pip
      run:
        - cartopy
        - cdo >=1.9.7
        - cdsapi
        - cf-units
        - cftime
        - cmocean
        - cython
        - dask
        - ecmwf-api-client
        - eofs
        - esmpy
        - esmvalcore 2.4.*
        - fiona
        - gdal
        - jinja2
        - joblib
        - lime
        - matplotlib-base
        - natsort
        - nc-time-axis
        - netCDF4
        - numpy
        - openpyxl
        - pandas
        - pyproj >=2.1
        - python >=3.7
        - python-cdo
        - pyyaml
        - rasterio  # replaces pynio
        - ruamel.yaml
        - scikit-image
        - scikit-learn
        - seaborn
        - seawater
        - shapely
        - xarray >=0.12.0
        - xesmf
        - xgboost
        - xlsxwriter
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-flake8
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-xdist
      imports:
        - esmvaltool
      commands:
        - pytest -n 2 --ignore="run_test.py" --ignore="tests/unit/test_docs.py" -k "not ([diagnostic.R] or [diagnostic.jl] or [diagnostic.ncl] or test_r_lint)"
        - esmvaltool --help
        - cmorize_obs --help
        - nclcodestyle --help
        - esmvaltool colortables --help
        - test_recipe --help

  # - name: esmvaltool-julia
  #   build:
  #     noarch: generic
  #     post-link: install-julia-deps
  #   requirements:
  #     run:
  #       - esmvaltool-python

  - name: esmvaltool-ncl
    build:
      noarch: generic
    requirements:
      run:
        - cdo >=1.9.7
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - imagemagick
        - ncl >=6.6
        - nco
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-flake8
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-xdist
      commands:
        - pytest -n 2 -k "[diagnostic.ncl]"

  - name: esmvaltool-r
    build:
      noarch: generic
    requirements:
      run:
        - cdo >=1.9.7
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - nco
        - r-base >=3.5
        - r-abind
        - r-akima
        - r-climdex.pcic
        - r-climprojdiags
        - r-docopt
        - r-dotcall64
        - r-functional
        - r-ggplot2
        - r-gridextra
        - r-lintr
        - r-logging
        - r-mapproj
        - r-maps
        - r-multiapply
        - r-ncdf4
        - r-ncdf4.helpers
        - r-pcict
        - r-plyr
        - r-rcolorbrewer
        - r-rcpp
        - r-s2dverification
        - r-snow
        - r-spei
        - r-styler
        - r-udunits2
        - r-yaml
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-flake8
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-xdist
      commands:
        - pytest -n 2 -k "[diagnostic.R] or test_r_lint"

  - name: esmvaltool
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        # - {{ pin_subpackage('esmvaltool-julia', exact=True) }}
        - {{ pin_subpackage('esmvaltool-ncl', exact=True) }}
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - {{ pin_subpackage('esmvaltool-r', exact=True) }}
    test:
      imports:
        - esmvaltool
      commands:
        - esmvaltool --help
        - esmvaltool recipes list
        - esmvaltool version
        - cmorize_obs --help
        - nclcodestyle --help
        - esmvaltool colortables --help
        - test_recipe --help

about:
  home: https://www.esmvaltool.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
  description: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.

extra:
  recipe-maintainers:
    - schlunma
    - zklaus
    - valeriupredoi
    - nielsdrost
    - bouweandela
